spring.application.name=order-service

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=mysql

# Tat auto-create schema vi dung Flyway
spring.jpa.hibernate.ddl-auto=none

# Port rieng vi 8080 da dung cho product-service
server.port=8081

# URL cua Inventory Service; integration tests override this with WireMock.
inventory.url=http://localhost:8082

spring.cloud.compatibility-verifier.enabled=false


# Springdoc OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
